pipeline {
    agent any

    environment {
        AWS_REGION     = "ap-south-1"
        AWS_ACCOUNT_ID = "207963326787"
        IMAGE_NAME     = "shopping-app"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    credentialsId: 'git-creds',
                    url: 'https://github.com/mrbhupendra1/CI-CD-project-repo.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh """
                        echo "[INFO] Building Docker image..."
                        docker build -t ${IMAGE_NAME}:latest ./shoping-app
                        docker tag ${IMAGE_NAME}:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:latest
                    """
                }
            }
        }

        stage('Push to AWS ECR') {
            steps {
                withAWS(region: "${AWS_REGION}", credentials: 'aws-credentials') {
                    sh """
                        echo "[INFO] Logging in to AWS ECR..."
                        aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

                        echo "[INFO] Pushing Docker image to ECR..."
                        docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:latest
                    """
                }
            }
        }

        stage('Deploy to VM2 (Testing)') {
            steps {
                sshagent(['ssh-credential-vm2']) {
                    sh """
                        echo "[INFO] Deploying to VM2..."
                        ssh -o StrictHostKeyChecking=no ubuntu@10.0.2.55'
                            docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:latest &&
                            docker stop ${IMAGE_NAME} || true &&
                            docker rm ${IMAGE_NAME} || true &&
                            docker run -d --name ${IMAGE_NAME} -p 3000:3000 ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:latest
                        '
                    """
                }
            }
        }

        stage('Deploy to VM3 (Production)') {
            steps {
                sshagent(['ssh-credential-vm3']) {
                    sh """
                        echo "[INFO] Deploying to VM3..."
                        ssh -o StrictHostKeyChecking=no ubuntu@10.0.2.220 '
                            docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:latest &&
                            docker stop ${IMAGE_NAME} || true &&
                            docker rm ${IMAGE_NAME} || true &&
                            docker run -d --name ${IMAGE_NAME} -p 3000:3000 ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:latest
                        '
                    """
                }
            }
        }
    }
}
