pipeline {
    agent any

    environment {
        AWS_REGION     = "ap-south-1"
        AWS_ACCOUNT_ID = "207963326787"
        ECR_REPO       = "shopping-app"
        IMAGE_NAME     = "shopping-app"
        IMAGE_TAG      = "latest"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/mrbhupendra1/CI-CD-project-repo.git',
                    credentialsId: 'git-credentials'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    echo "[INFO] Building Docker image..."
                    sh """
                        docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ./shoping-app
                        docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
                    """
                }
            }
        }

        stage('Push to AWS ECR') {
            steps {
                withAWS(region: "${AWS_REGION}", credentials: 'aws-creds') {
                    script {
                        sh """
                            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
                        """
                    }
                }
            }
        }

        stage('Deploy to VM2 (Testing)') {
            steps {
                sshagent(['vm2-ssh']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no ubuntu@10.0.2.55"
                            docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG} &&
                            docker stop shopping-app || true &&
                            docker rm shopping-app || true &&
                            docker run -d --name shopping-app -p 3000:3000 ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
                        "
                    """
                }
            }
        }

        stage('Deploy to VM3 (Production)') {
            steps {
                sshagent(['vm3-ssh']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no ubuntu@10.0.2.220 "
                            docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG} &&
                            docker stop shopping-app || true &&
                            docker rm shopping-app || true &&
                            docker run -d --name shopping-app -p 3000:3000 ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
                        "
                    """
                }
            }
        }
    }
}
